services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
